name: Generate ASCII Artwok

on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List Repo Files
          run: ls -ltra

        - name: Find ascii-script.sh
          run: find . -name "ascii-script.sh"

        - name: Check if ascii-script.sh exists
          run: test -f ascii-script.sh && echo "Found ascii-script.sh" || echo "ascii-script.sh not found"

        - name: Executing Cowsay Program
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
          
       