name: Generate ASCII Artwok

on:
    push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt install cowsay -y
        
        - name: Execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

        - name: upload file
          uses: actions/upload-artifact@v3
          with:
            name: dragon-artifact 
            path: dragon.txt

    
    test_job_2:

      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: download file
        uses: actions/download-artifact@v3
        with:
          name: dragon-artifact 

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

    deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps:
      - name: download file
        uses: actions/download-artifact@v3
        with:
          name: dragon-artifact 
          
      - name: Read file
        run: cat dragon.txt
        
      - name: Deploy
        run: echo Deploying........

          
       